#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PI_AGENT_DIR="${PI_AGENT_DIR:-$HOME/.pi/agent}"
CONFIG_FILE="${PI_AGENT_CONFIG:-$REPO_ROOT/.pi-agent-selection.mk}"

need_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd" >&2
    return 1
  fi
}

need_cmd git
need_cmd node
need_cmd npm
need_cmd make

echo "Detected versions:"
echo "  node: $(node --version)"
echo "  npm:  $(npm --version)"
echo "  git:  $(git --version)"

echo "Ensuring ~/.pi agent directory exists: $PI_AGENT_DIR"
mkdir -p "$PI_AGENT_DIR"

if [[ ! -f "$CONFIG_FILE" ]]; then
  cat > "$CONFIG_FILE" <<EOF
# Generated by bootstrap
ENABLED_SKILLS="all"
ENABLED_EXTENSIONS="all"
EOF
  echo "Created default config: $CONFIG_FILE"
else
  echo "Using existing config: $CONFIG_FILE"
fi

"$REPO_ROOT/scripts/install-pi-agent.sh"

echo "Bootstrap complete."
