#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${PI_AGENT_CONFIG:-$REPO_ROOT/.pi-agent-selection.mk}"
SKILLS_SRC="$REPO_ROOT/skills/pi-skills"
EXT_SRC="$REPO_ROOT/extensions"

list_dirs() {
  find "$1" -mindepth 1 -maxdepth 1 \( -type d -o -type l \) -exec basename {} \; | sort
}

AVAILABLE_SKILLS="$(list_dirs "$SKILLS_SRC" | tr '\n' ' ')"
AVAILABLE_EXT="$(list_dirs "$EXT_SRC" | tr '\n' ' ')"

SKILLS="${SKILLS:-}"
EXTENSIONS="${EXTENSIONS:-}"

if [[ -z "$SKILLS" || -z "$EXTENSIONS" ]]; then
  cat <<EOF
Usage:
  SKILLS="all" EXTENSIONS="all" make configure
  SKILLS="brave-search browser-tools" EXTENSIONS="web-access" make configure

Available skills:
  $AVAILABLE_SKILLS

Available extensions:
  $AVAILABLE_EXT
EOF
  exit 1
fi

cat > "$CONFIG_FILE" <<EOF
# Generated by scripts/configure-pi-agent.sh
# Values: 'all' or space/comma-separated names
ENABLED_SKILLS="$SKILLS"
ENABLED_EXTENSIONS="$EXTENSIONS"
EOF

echo "Wrote $CONFIG_FILE"
cat "$CONFIG_FILE"
